### ISSUE TITLE
Estrutura collections inicial

### ISSUE THREAD

**Issue by zerolx** [sosVacinaCampos/sosVacinaCampos#1]

**Comment by zerolx** [comment]
vacinacao: 
---- data (date)
---- qtd_vacinado (number)
---- qtd_planejado (number)

agendamento:
---- local_operacao (string)
---- status (string)
---- data (date)
---- turno (string)
---- nome_paciente (string)
---- cpf_paciente (string mas o conteudo apenas numero)
---- idade_paciente (number)
---- whatsapp_paciente (string mas o conteudo apenas numero formatado (+5522) )

**Comment by LeoFC97** [comment]
local_operacao  vai ser o nome do local ou tem algum ID indexando os locais?

**Comment by LeoFC97** [comment]
Sobre o whatsapp_paciente, acho que a gente deva aceitar dds fora do 22. Eu mesmo moro em campos  a 5 anos mas meu DDD é 21, isso é bem comum aqui

**Comment by zerolx** [comment]
Foi só um exemplo da formatação no front (+15 código de pais, 22 código da
cidade)

Em qui., 18 de mar. de 2021 14:12, Leonardo Costa ***@***.***>
escreveu:

**Comment by zerolx** [comment]
O local_operscao é o nome do local apenas

Em qui., 18 de mar. de 2021 14:23, Galba Arueira ***@***.***>
escreveu:

**Comment by d3rf** [comment]
> vacinacao:
> ---- data (date)
> ---- qtd_vacinado (number)
> ---- qtd_planejado (number)
> 
> agendamento:
> ---- local_operacao (string)
> ---- status (string)
> ---- data (date)
> ---- turno (string)
> ---- nome_paciente (string)
> ---- cpf_paciente (string mas o conteudo apenas numero)
> ---- idade_paciente (number)
> ---- whatsapp_paciente (string mas o conteudo apenas numero formatado (+5522) )

Sugiro colocar no doc da collection vacinacao um map com os dados do local/turno/idade para facilitar

**Comment by LeoFC97** [comment]
![image](https://user-images.githubusercontent.com/33994116/111835898-55459580-88d4-11eb-97a8-030e72ba48d9.png)
![image](https://user-images.githubusercontent.com/33994116/111836297-ce44ed00-88d4-11eb-83a6-c34bb82c89c7.png)
